baseurl = "http://yoshiharuyamashita.com"
languageCode = "en-us"
title = "Yoshiharu Yamashita"
theme = "blackburn"
author = "Yoshiharu Yamashita"
copyright = "&copy; 2016. All rights reserved."
canonifyurls = true
paginate = 10

[indexes]
  tag = "tags"
  topic = "topics"

[params]
  # Shown in the home page
  subtitle = "Software Engineer / Freelance Translator / Wannabe Freestyle Footballer"
  github = "yoshiharuyamashita"
  googleAnalytics = "UA-72514969-1"
  # CSS name for highlight.js
  highlightjs = "androidstudio"
